name: Blur Master Branch

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: submodules
      run: git submodule update --init
    - name: make
      run: make release-cross-linux-x86_64
